import { ArrowRight, ArrowUpRight, BadgeCheck, BookOpen, BrainCircuit, BriefcaseBusiness, ChevronRight, CirclePlay, Clock3, GraduationCap, Menu, MoveUpRight, Play, ShieldCheck, Sparkles, UsersRound } from 'lucide-react'

const courses = [
  { number: '01', title: '从内容到到院：美业线上获客实战', tag: '获客增长', lessons: '12 节课', progress: 72, color: 'rose' },
  { number: '02', title: '直播间成交设计与团队 SOP', tag: '直播运营', lessons: '9 节课', progress: 34, color: 'sand' },
  { number: '03', title: '让 AI 成为你的内容搭档', tag: 'AI 工具', lessons: '6 节课', progress: 0, color: 'sage' },
]

function Brand() { return <a className="brand" href="/"><span className="brand-mark">景</span><span><b>景珩</b><small>美业增长研习社</small></span></a> }

function Header({ admin = false }: { admin?: boolean }) {
  return <header className="topbar"><Brand /><nav className="main-nav"><a href="/#method">课程体系</a><a href="/#tools">AI 工具</a><a href="/#about">关于研习社</a></nav><div className="nav-actions">{admin ? <a className="text-link" href="/">返回官网 <ArrowUpRight size={15}/></a> : <><a className="login-link" href="/learn">学员入口</a><a className="button button-dark button-small" href="/learn">进入研习社 <ArrowRight size={15}/></a></>}<a className="mobile-menu" href={admin ? '/' : '/learn'} aria-label={admin ? '返回官网' : '学员入口'}><Menu/></a></div></header>
}

function Landing() {
  return <><Header/><main>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/> 美业经营者的实战成长平台</div><h1>把流量做成<span>到院</span><br/>把经验变成<span>增长</span></h1><p>从内容获客、直播转化到团队交付，和一线实战团队一起，把每一步做成可以落地的经营方法。</p><div className="hero-actions"><a className="button button-dark" href="/learn">看看会员课程 <ArrowRight size={16}/></a><a className="button button-light" href="/#method"><CirclePlay size={17}/> 了解我们怎么教</a></div><div className="hero-proof"><div className="avatar-stack"><i>珩</i><i>研</i><i>习</i><i>社</i></div><span><b>面向真实经营场景</b><small>课程 · 陪跑 · AI 内容工具</small></span></div></div>
    <div className="hero-art"><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><div className="art-stamp"><span>JH</span><small>GROWTH<br/>STUDIO</small></div><div className="art-panel"><div className="panel-top"><span>GROWTH NOTE / 001</span><span>2026</span></div><div className="panel-title">增长<br/><em>有迹可循</em></div><div className="panel-line"/><div className="panel-bottom"><span>内容 → 线索 → 到院</span><span>景珩研习社</span></div></div><div className="floating-note"><Sparkles size={15}/><span>把方法带回你的门店</span></div><div className="art-index">A FIELD GUIDE FOR<br/>BEAUTY BUSINESS</div></div></section>
    <section className="trust-strip"><span>一线经营拆解</span><i/><span>可复用执行方法</span><i/><span>AI 内容效率工具</span><i/><span>从线索到交付</span></section>
    <section className="section method" id="method"><div className="section-heading"><div><div className="eyebrow">THE LEARNING PATH</div><h2>不是听完就算，<br/>而是带着问题来，带着方法走。</h2></div><p>围绕美业机构真正要解决的经营问题，把课程、练习和工具放在同一条学习路径里。</p></div><div className="method-grid"><article className="method-card"><span className="card-num">01 / 找到客户</span><div className="method-icon blush"><UsersRound/></div><h3>内容获客</h3><p>搭建门店内容节奏，明确选题、表达和线索承接动作。</p><a href="/learn">浏览课程 <ArrowUpRight size={15}/></a></article><article className="method-card"><span className="card-num">02 / 形成转化</span><div className="method-icon sand"><BriefcaseBusiness/></div><h3>直播与转化</h3><p>从直播间表达、咨询承接到到院服务，梳理关键环节。</p><a href="/learn">浏览课程 <ArrowUpRight size={15}/></a></article><article className="method-card"><span className="card-num">03 / 提高效率</span><div className="method-icon sage"><BrainCircuit/></div><h3>AI 内容协作</h3><p>用 AI 辅助构思、改写和整理，让团队更快完成内容初稿。</p><a href="/#tools">了解 AI 工具 <ArrowUpRight size={15}/></a></article></div></section>
    <section className="tools-band" id="tools"><div className="tools-copy"><div className="eyebrow eyebrow-light">AI WORKBENCH / PREVIEW</div><h2>好方法，要能<br/>更快地用起来。</h2><p>正在规划的美业 AI 工作台，将从选题灵感、短视频脚本、朋友圈表达和直播复盘等高频场景开始。</p><div className="tool-tags"><span>选题灵感</span><span>脚本初稿</span><span>直播复盘</span><span>门店 SOP</span></div><a className="button button-cream" href="/learn">查看学习入口 <ArrowRight size={16}/></a><small className="compliance-note"><ShieldCheck size={13}/> 用于经营和内容辅助，不替代专业医疗判断。</small></div><div className="tool-window"><div className="window-chrome"><span/><span/><span/><small>景珩 · 内容工作台</small></div><div className="window-content"><div className="window-label"><Sparkles size={14}/> 今日灵感</div><h3>“客户不是不想做，<br/>她只是还没想清楚。”</h3><p>围绕这个经营观察，生成一条真实、克制、能引发交流的内容初稿。</p><div className="prompt-row"><span>表达方向：门店经营洞察</span><ArrowUpRight size={15}/></div><div className="window-status"><span><i/> 草稿待编辑</span><span>内容工具预览</span></div></div></div></section>
    <section className="section about" id="about"><div className="about-mark">景<br/>珩</div><div className="about-copy"><div className="eyebrow">ABOUT THE STUDIO</div><h2>懂增长，也尊重<br/>每一家店的真实处境。</h2><p>景珩美业增长研习社，面向美业经营者和服务团队，提供实战课程、方法训练与内容工具。我们关注的不只是“怎么发”，更是流量之后如何承接、如何交付、如何长期经营。</p><a className="text-link" href="/learn">进入会员学习端 <MoveUpRight size={16}/></a></div><div className="about-stats"><div><strong>01</strong><span>先看真实问题</span></div><div><strong>02</strong><span>再练落地动作</span></div><div><strong>03</strong><span>回到经营现场</span></div></div></section>
    <section className="closing"><div className="eyebrow eyebrow-light">START WITH ONE CLEAR STEP</div><h2>把下一步，走得更清楚。</h2><p>从一门课开始，找到适合自己门店的增长动作。</p><a className="button button-cream" href="/learn">进入研习社 <ArrowRight size={16}/></a></section>
  </main><Footer/></>
}

function Learn() {
  return <><Header/><main className="dashboard"><aside className="learn-side"><Brand/><div className="side-label">学习空间</div><a className="side-item active"><BookOpen size={17}/> 我的课程</a><a className="side-item"><BrainCircuit size={17}/> AI 工作台 <span className="soon">规划中</span></a><a className="side-item"><BadgeCheck size={17}/> 学习记录</a><div className="side-bottom"><div className="profile-circle">景</div><span><b>景珩学员</b><small>演示账户 · 会员</small></span><ChevronRight size={16}/></div></aside><section className="learn-main"><div className="learn-top"><span>我的学习空间</span><button className="button button-dark button-small" onClick={()=>window.location.href='/'}>返回官网 <ArrowUpRight size={14}/></button></div><div className="welcome-row"><div><div className="eyebrow">MONDAY, 28 SEPTEMBER</div><h1>下午好，欢迎回来。</h1><p>把今天的一点时间，留给下一步增长。</p></div><div className="streak"><span>本周学习</span><b>02 <small>/ 05 天</small></b><div className="streak-bars"><i/><i/><i/><i/><i/></div></div></div><div className="continue-card"><div className="continue-image"><div className="play-circle"><Play fill="currentColor" size={17}/></div><span>FIELD NOTES · 03</span><div className="image-lines">内容<br/><em>到院</em></div></div><div className="continue-info"><div className="eyebrow">继续学习 · 获客增长</div><h2>从内容到到院：美业线上获客实战</h2><p>第 8 讲 · 让内容带来有效咨询</p><div className="progress-track"><i style={{width:'72%'}}/></div><div className="progress-meta"><span>已完成 8 / 12 节</span><span>约 18 分钟</span></div><button className="button button-dark" onClick={()=>alert('课程播放功能将在接入课程视频后启用。')}>继续学习 <ArrowRight size={16}/></button></div></div><div className="courses-heading"><h2>我的课程 <span>03</span></h2><a href="#courses">查看全部 <ArrowRight size={14}/></a></div><div className="course-list" id="courses">{courses.map(course=><article className="course-row" key={course.number}><div className={`course-thumb ${course.color}`}><span>{course.number}</span><BookOpen size={21}/></div><div className="course-info"><span className="course-tag">{course.tag}</span><h3>{course.title}</h3><small><CirclePlay size={13}/> {course.lessons}</small></div><div className="row-progress"><div className="progress-track"><i style={{width:`${course.progress}%`}}/></div><small>{course.progress?`已学 ${course.progress}%`:'尚未开始'}</small></div><button className="round-arrow" onClick={()=>alert('课程内容将在课程管理模块接入后展示。')} aria-label="打开课程"><ArrowUpRight size={17}/></button></article>)}</div><div className="learn-note"><ShieldCheck size={15}/> 这是可运行的前端演示。账号、会员权益、付费和真实课程内容尚未接入。</div></section></main></>
}

function Admin() {
  return <><Header admin/><main className="admin-page"><div className="admin-head"><div><div className="eyebrow">CONTROL ROOM / PREVIEW</div><h1>运营概览</h1><p>管理课程内容、学员和平台运营数据。</p></div><button className="button button-dark button-small" onClick={()=>alert('创建课程表单将在课程管理模块实现。')}>＋ 创建课程</button></div><div className="admin-cards"><article><span>会员学员</span><UsersRound/><strong>1,286</strong><small>演示数据 · 较上月 <b>+8.4%</b></small></article><article><span>已发布课程</span><GraduationCap/><strong>18</strong><small>5 门课程正在更新</small></article><article><span>本月课程收入</span><BriefcaseBusiness/><strong>¥ 86,420</strong><small>演示数据 · 较上月 <b>+12.6%</b></small></article><article><span>待处理事项</span><Clock3/><strong>07</strong><small>评论回复与内容审核</small></article></div><div className="admin-grid"><section className="admin-panel"><div className="panel-heading"><h2>近期课程</h2><a href="/learn">查看学习端 <ArrowUpRight size={14}/></a></div>{courses.map(c=><div className="admin-course" key={c.number}><span className={`course-dot ${c.color}`}/><b>{c.title}</b><small>{c.progress?`${c.progress}% 完成`:'草稿'}</small><button aria-label="编辑">···</button></div>)}</section><section className="admin-panel"><div className="panel-heading"><h2>平台待办</h2><span className="todo-count">3 项</span></div><div className="todo"><i/><span><b>完善课程介绍页</b><small>会员课程 · 内容更新</small></span><ArrowUpRight size={15}/></div><div className="todo"><i/><span><b>检查新学员反馈</b><small>学员服务 · 2 条待回复</small></span><ArrowUpRight size={15}/></div><div className="todo"><i/><span><b>AI 工作台接入评估</b><small>产品规划 · 待排期</small></span><ArrowUpRight size={15}/></div></section></div><div className="admin-disclaimer"><ShieldCheck size={15}/> 管理后台目前为 UI 演示，所有指标均为占位数据；接入真实业务 API 后再用于运营决策。</div></main></>
}

function Footer(){return <footer className="footer"><Brand/><span>© 2026 景珩美业增长研习社</span><div><a href="/learn">学员入口</a><a href="/admin">管理演示</a></div></footer>}

export default function App(){const path=window.location.pathname;return path.startsWith('/admin')?<Admin/>:path.startsWith('/learn')?<Learn/>:<Landing/>}
